name: Deploy to Hugging Face

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to HF Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://carolinasoares:$HF_TOKEN@huggingface.co/spaces/carolinasoares/urban_disaster_monitor space
          rm -rf space/*
          cp -r app/* space/
          cd space
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy automático" || echo "Nada para commitar"
          git push
